### ISSUE TITLE
Definition of INADDR_NONE in header file bloats final executable size

### ISSUE THREAD

**Issue by MHotchin** [arduino-libraries/Ethernet#128] opened 2020-03-07 03:31 UTC
Currently, IPADDRESS.H both declares and defines INADDR_NONE.

If a sketch has more than one file that includes IPAddress.h, then multiple copies of INADDR_NONE end up in the final executable.  Essentially, each CPP file gets its own copy as a global variable, at 6 bytes a pop.

If the declaration in IPAddress.h is changed to:
extern const IPAddress INADDR_NONE;

and a new definition is provided in IPAddress.cpp:
const IPAddress INADDR_NONE(0, 0, 0, 0);

then only one copy end up in the executable.

My sketch went from 2002 bytes 'Minimum Memory Usage' to 1888 bytes, a savings of 78 bytes in my case.

**Comment by Rotzbua** [comment] 2020-03-07 14:48
The `ethernet` library does not contain a `IPAddress.h/.ccp` .

It is part of the main arduino framework. I reported this years ago. It is fixed in the default arduino framework.

My last update was that the uno is  not (yet?) migrated to the default arduino framework.

Best

**Comment by per1234** [comment] 2020-03-07 19:34
Thanks for the explanation @Rotzbua.

Closing as duplicate of https://github.com/arduino/Arduino/issues/1007, which was fixed by https://github.com/arduino/ArduinoCore-API/commit/3dbd7d7d338ff2d93c8b9dd8c833967fdb69b7c6 (but has not yet propagated out to all the core libraries).

**Closed by per1234** 2020-03-07 19:34 UTC
